[package]
name = "bilicli_napi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
platform-napi = []

[dependencies]
ratatui = { version = "0.28" }
crossterm = { version = "0.28", features = ["event-stream"] }
tui-textarea = "0.6"
chrono = "0.4.38"
strum = "0.26.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json"] }
napi = { version = "2.16.9", features = ["async"] }
napi-derive = "2.16.11"
tokio = { version = "1.39", features = ["time", "sync", "macros"] }
futures = "0.3.30"
itertools = "0.13"
unicode-width = "0.1.13"

[build-dependencies]
napi-build = "2.1.3"

[profile.release]
lto = true
opt-level = "z"
strip = true
# panic = "abort"
codegen-units = 1
