[package]
name = "bilicli_napi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "bilicli-napi"
features = []

[features]
napi = []

[dependencies]
ratatui = { version = "0.28" }
crossterm = { version = "0.28", features = ["event-stream"] }
tui-textarea = "*"
unicode-width = "0.1.13"
chrono = "0.4.38"
strum = "0.26.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "blocking"] }
napi = { version = "2.16.9", features = ["tokio_rt", "napi4"] }
napi-derive = "2.16.11"

[build-dependencies]
napi-build = "2.1.3"
cfg_aliases = "0.2.1"

[profile.release]
lto = true
opt-level = "z"
strip = true
panic = "abort"
codegen-units = 1
