/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum AppState {
  Running = 0,
  Quitting = 1,
  Quit = 2
}
export const enum MsgType {
  Danmu = 0,
  SuperChat = 1,
  Gift = 2,
  GuardBuy = 3,
  UserAction = 4
}
export declare class Cli {
  constructor(roomId: number)
  get state(): Promise<AppState>
  run(): Promise<void>
  stop(): Promise<void>
  sendAttentionChange(attention: number): Promise<void>
  sendWatcherChange(watcher: string): Promise<void>
  sendLiveChange(live: boolean): Promise<void>
  sendMsg(t: MsgType, msg: string): Promise<void>
}
