/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum AppState {
  Running = 0,
  Quitting = 1,
  Quit = 2
}
export const enum MsgType {
  Danmu = 0,
  SuperChat = 1,
  Gift = 2,
  GuardBuy = 3,
  UserAction = 4
}
export declare function restoreTerminal(): void
export declare class Tui {
  constructor(roomId: number, cookie?: string | undefined | null)
  get state(): Promise<AppState>
  /**
   * # Safety
   * This function is marked as unsafe because it requires exclusive access to the state.
   */
  run(): Promise<void>
  /**
   * # Safety
   * This function is marked as unsafe because it requires exclusive access to the state.
   */
  stop(): Promise<void>
  /**
   * # Safety
   * This function is marked as unsafe because it requires exclusive access to the state.
   */
  sendAttentionChange(attention: number): Promise<void>
  /**
   * # Safety
   * This function is marked as unsafe because it requires exclusive access to the state.
   */
  sendWatcherChange(watcher: number): Promise<void>
  /**
   * # Safety
   * This function is marked as unsafe because it requires exclusive access to the state.
   */
  sendLiveChange(live: boolean): Promise<void>
  /**
   * # Safety
   * This function is marked as unsafe because it requires exclusive access to the state.
   */
  sendMsg(t: MsgType, msg: string): Promise<void>
}
